Improve Tree Page-Map Return
Code-4-Community/speak-for-the-trees-frontend pull request #108
Opened 2021-09-19 21:42 UTC by SofieDunt

## Why

[ClickUp Ticket](https://app.clickup.com/t/1dk42tb)

Users are having difficulty switching between the map and tree pages. Improves user flow by opening the tree page in a new tab and opening the map at the street zoom level at the site location via the 'Return to Tree Map' button.

## This PR

- use Link target to open tree page in a new tab
- use location state to pass the map the site's location and the zoom level to go to
  - ensure layer visibility is initialized according to the zoom level rather than assuming the map is zoomed out
- clean up codebase by putting the redirect button under themed components

## Verification Steps

 
Tested going from the map to the tree page (check that page opens in a new tab) and returning to the map (check that the map is zoomed in at the site's location)
Tested going from a tree page to the map via the return button (check that the map is zoomed in at the site's location)

2021-09-20 18:44 UTC, willmt80 commented
It looks like coveralls is down so hopefully this build will pass once it's back up.

2021-09-20 18:58 UTC, willmt80 requested changes
Left a couple of suggestions/questions, other than that looks good!

2021-09-20 18:58 UTC, willmt80 commented on src/components/mapPageComponents/logic/init.ts
> +  visible: boolean,
👍

2021-09-20 18:58 UTC, willmt80 commented on src/components/mapPageComponents/mapView/index.tsx
> +              ? { lat: location.state.lat, lng: location.state.lng }
Not too familiar with useLocation. Is it possible to set the initial state to BOSTON so we can avoid this ternary operator?

2021-09-20 18:58 UTC, willmt80 commented on src/components/themedComponents/index.tsx
> +export const ReturnButton = styled(LinkButton)`
👍

2021-09-20 18:58 UTC, willmt80 commented on src/containers/treePage/index.tsx
> +const ReturnButton = styled(Button)`
Can we give the link button an optional state argument? that way we don't need to defined this style or link functionality below more than once. Plus I'm sure we'll wind up reusing this for the blocks in the future.

2021-09-22 19:21 UTC, adriannaliu approved these changes

2021-09-24 17:38 UTC, willmt80 approved these changes
Looks good!

2021-09-24 17:38 UTC, willmt80 commented on src/components/linkButton/index.tsx
> +    <Button {...rest}>
🔥

2021-09-27 19:39 UTC, merged