Emailer: Load HTML templates from S3
Code-4-Community/speak-for-the-trees-frontend pull request #334
Opened 2024-03-17 17:08 UTC by CiciLing

## Checklist

- [ ] 1. Run `yarn run check`
- [ ] 2. Run `yarn run test`

## Why

Resolves #259 

This allows the user to choose the email template and apply it to the email they're sending. The user can make edits to the template. 

## This PR

We passed in a form instance to sendEmailForm/index.tsx from email/index.tsx. 

## Screenshots
![Screenshot 2024-03-17 at 1 02 15 PM (1)](https://github.com/Code-4-Community/speak-for-the-trees-frontend/assets/102868495/eb87d904-0d29-4c8f-ba50-cbfe6e0e46fa)

## Verification Steps

Choose the template from the select template dropdown and a template in html should appear in the email body.

2024-03-20 01:41 UTC, huang0h commented on src/components/forms/sendEmailForm/index.tsx
> +  const SendEmailForm: React.FC<SendEmailFormProps> = ({ emails }) => {
⛏️ Looks like you have some errors (from merging) - make sure to get rid of this extra declaration of `SendEmailForm`!

2024-03-20 01:43 UTC, huang0h commented on src/components/forms/sendEmailForm/index.tsx
> +  const SendEmailForm: React.FC<SendEmailFormProps> = ({ emails }) => {
Also make sure to remove line 50:
```const [sendEmailForm] = Form.useForm();```
since we're passing the form instance as a prop now

2024-03-20 02:00 UTC, huang0h commented on src/components/forms/sendEmailForm/index.tsx
>          <Input.TextArea rows={8} placeholder={t('body_placeholder')} />
⛏️ Can we also remove this extra `TextArea`? There's two text areas here:

![image](https://github.com/Code-4-Community/speak-for-the-trees-frontend/assets/68914997/055dc6d9-03b1-4a44-82b7-2032c77d60dd)

2024-03-20 02:08 UTC, huang0h commented on src/containers/email/index.tsx
> +        setTemplateNames([defaultTemplate]);
⛏️ Can we add an error message here in the `catch` (same for `fetchTemplateData`? Something like the `message.error()` call in [this function ](https://github.com/Code-4-Community/speak-for-the-trees-frontend/blob/a9c31c362a83a278cdce864b9c92df18ed6ef61f/src/components/forms/sendEmailForm/index.tsx#L71) would do - if something fails on our end, it's better to explicitly tell the user that an error happened than to fail silently and have them guess at why something's not working

2024-03-20 02:09 UTC, huang0h requested changes
Overall looks good! Just have a few small comments

2024-03-31 23:04 UTC, CerberusLatrans commented
<img width="1055" alt="Screenshot 2024-03-31 at 7 04 15 PM" src="https://github.com/Code-4-Community/speak-for-the-trees-frontend/assets/52577512/9f15b5ae-3d8d-40c0-8abe-32a7f02238da">
tested error message when loading empty html

2024-04-03 03:02 UTC, huang0h approved these changes
lgtm, nice work! A couple extra notes:
- You might need to just re-run the build checks to get them to pass
- When you merge, I suggest choosing the "squash and merge" option (see pic) from the dropdown - if you're not familiar with this, it'll basically combine all of your commits on this branch into a single commit that gets merged into master. This way the commit history doesn't get clogged up with your commits from while you were working

![image](https://github.com/Code-4-Community/speak-for-the-trees-frontend/assets/68914997/e272deb8-c661-435a-ba44-5737e84919aa)

2024-04-07 19:33 UTC, closed without merging